### ISSUE TITLE
Error: secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by jerryborn** [BTP-Sem-6/Explora-Backend#39]
When I try to register a user, it occurs!

D:\travel site\Explora-Backend-main\node_modules\jsonwebtoken\sign.js:101
    throw err;
    ^

Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (D:\travel site\Explora-Backend-main\node_modules\jsonwebtoken\sign.js:105:20)
    at D:\travel site\Explora-Backend-main\controllers\user.controller.js:117:31
    at D:\travel site\Explora-Backend-main\node_modules\bcryptjs\dist\bcrypt.js:297:21
    at D:\travel site\Explora-Backend-main\node_modules\bcryptjs\dist\bcrypt.js:1353:21
    at Immediate.next (D:\travel site\Explora-Backend-main\node_modules\bcryptjs\dist\bcrypt.js:1233:21)
    at processImmediate (node:internal/timers:466:21)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jerryborn** [comment]
ok, I find it just because of none secret key! lol
